### ISSUE TITLE
Setting the Tracking Space Type to Stationary causes a black screen (Oculus GO)

### ISSUE THREAD

**Issue by KlingOne** [ExtendRealityLtd/VRTK#1977]
### Environment

* Source of VRTK: GitHub
* Version of VRTK: v4 Github master
* Version of the Unity: 2019.1.0b7
* Hardware used: Oculus GO
* SDK used: UnityXR

### Steps to reproduce

Change the TrackingSpaceType of the UnityXRConfigurator to Stationary via the Unity Editor and start the example scene.

### Expected behavior

Should be able to see the level

### Current behavior

The level is visible for a split second and then the screen becomes black.
This does not happen if the TrackingSpaceType is set to RoomScale. But with RoomScale the Oculus GO controller does not work (but this may be intended because of the 3 DOF?).

**Comment by thestonefox** [comment]
I have a feeling this is either related to

https://github.com/ExtendRealityLtd/VRTK/issues/1974

or 

https://github.com/ExtendRealityLtd/VRTK/issues/1972

I will check and update this ticket.

**Comment by thestonefox** [comment]
Ok no, this isn't related to those issues.

It's related to the UnityXRCameraRig setup.

By default the UnityXR TrackedPoseDriver is set up to track position and rotation of gameobjects, i.e. track them in 6 degrees of freedom. because the Oculus Go is only 3dof on both headset and controller then positional tracking is going to always set them to a position of 0,0,0.

So the solution is:

Select `UnityXRCameraRig` prefab and on the `UnityXRConfigurator` select `TrackingSpaceType = Stationary`

Then expand the `UnityXRCameraRig` prefab and for each of the TrackedPoseDriver components found on `HeadAnchor` `LeftAnchor` `RightAnchor` change the `Tracking Type` to equal `Rotation Only`

This prevents it from forcing the position to 0,0,0

however, the position is still 0,0,0 so you need to manually give your `HeadAnchor` GameObject's Transform a position, so set it to something like `1.5` and then set up the `LeftAnchor` and `RightAnchor` position as well so they track near the headset.. something like

`LeftAnchor` -> `-0.25, 1.2, 0.1`
`RightAnchor` -> `0.25, 1.2, 0.1`

RIght now I can't think of a better way of automating this as we're just setting up predefines. So maybe in the future a good way of solving this would be to have a wizard type thing that set up the UnityXRCameraRig based on a predefinition.

Alternatively, using the Oculus Integration SDK should handle that stuff naturally anyway.
