### ISSUE TITLE
controller(alias) can not move with LWRP

### ISSUE THREAD

**Issue by MCsentic** [ExtendRealityLtd/VRTK#1982]
### Environment

* Source of VRTK: GitHub
* Version of VRTK : latest from github ( v4 )
* Version of the Unity software : Unity 2018.3.10f1
* Hardware used : HTC Vive
* SDK used : OpenVR(Desktop) 1.0.5
* LWRP version : 4.10.0-preview

### Steps to reproduce

1. Create a new project with LWRP
2. Follow the docs to set up the project and install VRTK
3. Follow the guide to add a UnityXRCameraRig
4. Follow the guide to add a TrackedAlias and give avatar to cam&controller.

### Expected behavior

When you move yourself or controller ,you can see avatar moving in scene and coordinate changed in hierachy ( like running in default 3D template)

### Current behavior

avatar can not move and coordinate not change

**Comment by Hooooyu** [comment]
Woooo~

**Comment by thestonefox** [comment]
LWRP isn't supported at present

**Comment by ROBYER1** [comment]
Will there be support for LWRP?

**Comment by thestonefox** [comment]
@ROBYER1 maybe in the future if/when LWRP settles down.

**Comment by jmackenzie68** [comment]
"In case somebody else find this, one way of fixing this issue is to change the Moment Processor moment to something else then PreRender or PreCull. Putting it to normal Update fixed the issue for me for now at least. Go to TrackedAlias - Internal - MomentProcessor and change Process Moment" - datwr @ https://www.reddit.com/r/vrdev/comments/bvfyke/vrtk_4_beta_and_unitys_lwrp_for_vr/

**Comment by JuanJSAR** [comment]
Here you can find the solution I made when I had the problem ... it is the same one you find on redit but more direct. [https://pastebin.com/KirBN21x](url)
