### ISSUE TITLE
Rigidbody Tracked Interactables lag way behind Axis Movement

### ISSUE THREAD

**Issue by thestonefox** [ExtendRealityLtd/VRTK#1992]
### Environment

* Source of VRTK: GitHub master
* Version of VRTK: v4 beta
* Version of the Unity software: 2019.1
* Hardware used: Oculus
* SDK used: UnityXR

### Steps to reproduce

1. in the example scene change the hammer follow type to `FollowRigidbody`
2. start the scene and switch to axis control
3. grab the hammer and move with axis control

### Expected behavior

The hammer should follow the controller without any lag

(see v3.3 functionality)

![goodfollow](https://user-images.githubusercontent.com/1029673/56830984-ce125300-685f-11e9-8ce7-e1d2d5ce9b7e.gif)

### Current behavior

The hammer lags behind the controller considerably

![badfollow](https://user-images.githubusercontent.com/1029673/56830745-0ebd9c80-685f-11e9-95ce-0dfcd9f32645.gif)

**Comment by thestonefox** [comment]
### Investigation

The AxisToVector3 Moment Processing is by default in the Update moment so the axis is changing at a different rate to the rigidbody being moved (which is in fixed update).

Moving the moment to FixedUpdate does help a bit

(see here)
![mehfollow](https://user-images.githubusercontent.com/1029673/56831251-7a543980-6860-11e9-9766-63f0ae590c58.gif)

But it still has a fundamental initial lag.

I thought this may be due to the `Unity 1D Axis Action` performing it's check in a simple `Update` but even manually changing it to `FixedUpdate` doesn't remove the lag.

Even with a simple script that just does a position update of a GameObject in a fixed update doesn't remove this lag so my assumption is something is up with the object follow perhaps?

**Comment by thestonefox** [comment]
The issue is a race condition in the fixed update routine.

If the Rigidbody Follow FixedUpdate processes before the AxesToVector3 FixedUpdate (via their respective MomentProcessors) then the issue occurs.

However, if the AxesToVector3 processes before the RigidbodyFollow then it works fine.

This can be confirmed by disabling the moment processor on the RigidbodyFollow and adding the MomentProcess from the RigidbodyFollow to the AxesToVector3 MomentProcessor List (in the second element slot).

This ensures the FixedUpdate processes the axis movement before processing the rigidbody follow and removes the issue.

**Comment by thestonefox** [comment]
Also due to the way the tracked alias following works, if it's set to PreRender then there's additional lag because the tracked object follows the alias which follows the actual controller so everything seems to need to be put onto FixedUpdate and processed via the same MomentProcessor to get around any race conditions.

**Comment by thestonefox** [comment]
Moving all of the relevant follow processes to fixed update and in the correct sequence does work (but is a clunky workaround)

![image](https://user-images.githubusercontent.com/1029673/56846738-b02e0800-68ca-11e9-86d9-b4e2a353051d.png)

This is all in the AxesToVector3 moment processor:

* Do AxesToVector3 movement first
* Then move play area to follow alias
* Then move controller alias to follow tracked controller
* Finally move tracked object to follow controller alias

![workaroundfollow](https://user-images.githubusercontent.com/1029673/56846758-e10e3d00-68ca-11e9-8613-b391dc3b0343.gif)

**Comment by thestonefox** [comment]
Not a bug, just needs things reconfiguring to work correctly (will cover in a future tutorial on the Academy)

**Comment by HugoCortell** [comment]
Did you ever get around covering it? I would love to know more.

**Comment by HugoCortell** [comment]
It appears a lot has changed since.
For starters `AxesToVector3 moment processor` does not exist and it appears that moment processors cannot be changed like on the image above either.
Below is the only moment processor I was able to locate within axis move.
![image](https://user-images.githubusercontent.com/59887727/95219444-aade2800-07f5-11eb-97c6-68cb27451412.png)
I went ahead and set up the necessary components as far as I am aware
![image](https://user-images.githubusercontent.com/59887727/95219865-28a23380-07f6-11eb-8af7-aa8bb95b5d8b.png)
Surprisingly, it actually runs in-engine so I had slightly-higher-than-no hope for the build.

Wow holy shit it actually worked.
The only issue now is the fact that id have to manually set it up for every level and lord knows if I'm even setting it up correctly, I have many questions such as "do I need to disable the other moment processor?".
I will probably be contacting you guys via discord to talk further about this.
