### ISSUE TITLE
Can't teleport using simulated camera rig

### ISSUE THREAD

**Issue by afonseca08** [ExtendRealityLtd/VRTK#2000]
### Environment

* Github
* c4c04852cfc31dba20136a587630ba4be4149c95
* 2019.1.0f2
* Editor
* Oculus

### Steps to reproduce

1. Open the sample scene
2. Run in editor and select Simulated CameraRig from the CameraRig Switcher UI
3. Middle click and hold to bring up the teleport UI
4. Try left or right mouse button to activate teleport

### Expected behavior
Either mouse button activates teleport

### Current behavior

Neither mouse button activates teleport

**Comment by thestonefox** [comment]
Changing the `VRTK Prefabs -> Controller Actions -> Right Controller -> Pointers -> SelectWithPointer -> BooleanAction -> Sources -> Element1` to either Mouse0 or Mouse1 will fix it.

However, when teleporting and rotating, the WASD keys for play area movement no longer represent the correct direction so this should probably be looked into too.

**Comment by thestonefox** [comment]
I think the fix for the wasd keys is the
`SimulatedCameraRig -> Internal -> MovementControl -> AliasObjects -> Player` components

shouldn't change the SimulatedCameraRig nor should they rotate the `AliasObjects` as these aren't representing what really happens in the scene,

Instead, if a TrackedAlias is injected into the Simulator then it should be modifying the PlayAreaAlias just like the other scripts do.

![image](https://user-images.githubusercontent.com/1029673/57362847-95377f80-7177-11e9-8a88-bd16d606b88d.png)

This should be handled at runtime by the SimulatorConfigurator and if the TrackedAlias is removed then it should resort back to referencing the SimulatedCameraRig and AliasObjects.

**Comment by thestonefox** [comment]
I've actually changed my mind again on this. The actual usage of the WASD keys should not be to move the play area, because you can't physically move your play area using VR equipment, you simply walk around your play area, therefore the WASD keys should only move the Headset/Controllers around the stationary play area, and there should be no need for a TrackedAlias being injected at all.

**Comment by thestonefox** [comment]
This has been fixed now in the latest GitHub master

**Comment by quangnv2002** [comment]
Can you make more than about Simulator CameraRig ?
