### ISSUE TITLE
When set rig rotation through teleport in script - Next teleport through controller resets the rotation to the initial (Possible Duplicate?)

### ISSUE THREAD

**Issue by Mechandrius** [ExtendRealityLtd/VRTK#2002]
### Environment

Unity 2019.1
Vrtk latest pull
SteamVR 2.x

### Steps to reproduce

Use a normal teleport (Instant)
Set teleport in script with custom rotation fex 180° turn. Teleport afterterwards with controller.

### Expected behavior

After the controller teleport you are facing the direction as you teleport towards.

### Current behavior

After the teleport you turned back the 180° you set and look in an unexpected direction.

**Comment by thestonefox** [comment]
This isn't a bug. This is because the rotation is determined by the teleport data given to it.

So if your cursor pointer is set to a rotation of 0 and your teleporter facade is digesting rotations then next time you teleport with your pointer it will use the cursor rotation (which is 0)

I recommend you ensure you're on the latest version of VRTK from github and untick the `Apply Destination Rotation` option on the `TeleporterFacade`

**Comment by Mechandrius** [comment]
Ok, it works.

            TelepoterFacade.ApplyDestinationRotation = true;
            TelepoterFacade.Teleport(tfData);
            TelepoterFacade.ApplyDestinationRotation = false;

Allows me to make an initial rig set and later have normal teleportation behaviour
