### ISSUE TITLE
Enabling/Disabling Interactables inside an Interactor's radius causing large framerate drop

### ISSUE THREAD

**Issue by Liens1** [ExtendRealityLtd/VRTK#2005]
### Environment

*Source of VRTK (GitHub).
*Version of VRTK (v4 Github master).
*Version of the Unity software (Unity 2019.1.1f1).
*Hardware used (Oculus).
*SDK used (UnityXR).

### Steps to reproduce

1. Take an `Interactable.Primary_Grab.Secondary_Swap` and drop it into the scene.
2. Shrink the `Interactable` to something small like 0.01, 0.01, 0.01 (small enough for 4 of them to fit inside an Interactor's radius).
3. Duplicate the small `Interactable` 3 times, for 4 total.
4. Position the `Interactor` so it is encompassing all 4 `Interactable`s.
5. Enable/Disable all 4 `Interactable`s at once repeatedly, after a short time the framerate will drop severely.

NB: I'm guessing this happens even with just 1 `Interactable`, but it takes a lot more enables/disables to drop the framerate significantly.

### Expected behavior

No frame drop.

### Current behavior

Massive frame drop.

**Comment by Liens1** [comment]
Note that step 5 must be repeated several times.

**Comment by thestonefox** [comment]
I think i know what the problem is.

The Interactor holds a collection of objects it's colliding with, when you collide with something and then disable that object it doesn't perform the collision exit within Unity.

So when you disable, the Interactor thinks the object is still being collided with, then when you re-enable it, a new collision event occurs and it adds that to the interactor collection too.

The more colliders and the more enable/disables, the bigger this list will grow.

Essentially we need to make sure the list is managed so it only is concerned with active game objects.

I think one solution may be simply, if the list is being iterated, just discard any inactive gameobjects as they can't be valid collisions.

**Comment by thestonefox** [comment]
@Liens1 just try this for a quick fix to see if it resolves the lag for you:

Open `ActiveCollisionsContainer.cs`

and in the `Add` method update it so it does a `Contains` check:

```
public virtual void Add(CollisionNotifier.EventData collisionData)
{
    if (Elements.Contains(collisionData) || !IsValidCollision(collisionData))
    {
        return;
    }
```

This will prevent it from flooding the collection with the same object, which should stop the quick lag....

However, it doesn't solve the overall problem of now there are active collisions that aren't actually active because either side of the collision can be disabled and therefore the collision is not active.

**Comment by Liens1** [comment]
Hm ok I tried that out, there's still frame drop but it's not as severe. So it seems to be at least limited for the moment

**Comment by thestonefox** [comment]
Well with that temp fix, it won't be populating the list over and over again, however if you touch multiple items at the same time the interactor will sort the list of touched items into "which object is nearest to the interactor" to determine which one to grab.

The more items your touching the bigger the list so the longer the sort. If you don't care about grabbing the nearest thing and just care about grabbing at least 1 thing you're touching then you could disable/bypass the `Nearest Sorter` on the Interactor so it wouldn't take that perf hit of that logic too.

**Comment by thestonefox** [comment]
The fundamental issue here though is caused by a Unity bug where Unity does not recognise disabling/destroying a GameObject as a collision exit.

So if you disable a colliding object you get no CollisionExit
But if you reenable the colliding object you get a new CollisionEnter

Therefore the CollisionNotifier/CollisionTracker in Zinnia know something has started colliding, but never knows it stops colliding, but is told it started colliding again.

This means the collision exit never occurs and puts everything out of sync. We need to come up with some work around for this extremely long standing Unity bug to make sure CollisionExit happens when components are Disabled/Destroyed.

**Comment by Liens1** [comment]
Would your earlier idea about removing any disabled gameobjects work, or would it still be out of sync because the lack of an exit has already occurred?

Could you call some Zinnia code for `CollisionExit` inside an `Interactable`'s `OnDisabled` method?

**Comment by thestonefox** [comment]
Yes removing the disabled items would work but that then requires polling the whole list every frame to check for disabled items which is not an acceptable perf hit.

Also, yes we could check the disabled on the interactable but then the actual underlying zinnia component is still broken and we're just patching over it.

We have an idea at the moment of resorting to magic and adding a component to the collider game object on enter that has a reference to the component that created it, then when the colliders game object is disabled then the magic component calls exit and removes itself.

The problem with this is it doesn't help with if you disable the collider component because it's only going to monitor the game object hierarchy state.

This may be the best solution though with that caveat that we'll have to accept

**Comment by Liens1** [comment]
I've found another issue, disabling the `Interactable`'s GameObject(specifically the Collider) while it is grabbed makes that hand unable to grab that specific `Interactable` anymore. Even after the object is ungrabbed. Re-enabling the GameObject makes it grabbableby that hand once more.

**Comment by thestonefox** [comment]
I don't understand how can you grab something if it's disabled?

**Comment by Liens1** [comment]
Sorry to clarify, the `Interactable` has 2 colliders and 2 meshes on it, and I've disabled the one that was used to grab it. Along with that one mesh

**Comment by thestonefox** [comment]
I wouldn't consider that a bug, you're breaking functionality doing that because it's trying to track a collider that you're swapping out for something it doesn't know about.

**Comment by Liens1** [comment]
I would have thought that it would still be grabbable by the remaining collider though? The problem is that the collider is disabled before Ungrab. I tried to disable the collider inside LastUngrabbed, but that seems to be too early still.

**Comment by thestonefox** [comment]
Why are you disabling the tracked collider? Instead turn it to trigger or disable it's physics collisions so it is still tracked. Alternatively you'd have to manually track the new collider

**Comment by Liens1** [comment]
I'm not replacing it with the second collider, the Interactable is in 2 parts, when I ungrab the Interactable it disables the mesh and collider (same gameobject) and finishes the ungrab normally. To create a 'it broke' type visual effect.

Thanks though I'll try the trigger approach

**Comment by Liens1** [comment]
Great that works thanks. It's good to know the alternative to disabling colliders here is triggers. I'm not used to working that way

**Comment by thestonefox** [comment]
Unity doesn't handle disabling stuff well 🤣 that's half the problem with this original bug in the first place
