### ISSUE TITLE
Climbing - Grip Strength

### ISSUE THREAD

**Issue by xEvoGx** [ExtendRealityLtd/VRTK#397]
This one is pretty obvious and works great in **The Climb**. Essentially if you're holding onto a climb point with only one controller, you begin to tire, losing stamina, and whenever you hold climb point(s) with both controllers, your stamina increases. Losing all your stamina means you automatically fall.

Another element that detracts from the presence of climbing a bit is being able to 'hold' yourself up and away from a climbing surface with one hand, your arm outstretched in front of you, which is obviously impossible IRL. In other words, the further away the player is from the 'wall' (test the controllers offset from the HMD along X and Z) and increase the stamina drain proportionally. Y is unaffected of course since that's merely reaching up or down. This would simulate the body being supported realistically, and require the player to stay close to the climbing surface to maintain stamina. If in fact they do reach out along X and/or Z to grab an out of the way climbing point, they take that risk knowing they could lose their grip if they fail to reach before stamina hits zero. Adds tremendously to the risk reward element and makes climbing a challenging and fun mechanic.

Cheers

**Comment by mattboy64** [comment]
This could be cool. I purposefully left it out of the climbing system to avoid cluttering it up, but adding a VRTK_GripStrength component to each hand would be pretty cool. My suggestion would be to do it that way and check for climb grab events. You could even add a GUI interface through it. I'd love to see somebody flesh this out.

**Comment by sidcitris** [comment]
I just put in a pull request for this feature request, but thought I would explain what I added. The script extends the existing VRTK_PlayerClimb script and adds a few things. 

First I added a Min Reach and Max Reach value. Stamina falls when the player is holding a climbable object with a single hand. If the distance from the controller hand to the HMD in the XZ plane is less than the minimum reach, stamina is not reduced. If the distance is greater than the max reach, stamina is reduced at the maximum rate. 

Stamina Recovery Rate is the speed at which stamina is regenerated. I also made it so stamina regenerates twice as fast when the player isn't climbing compared to when they are holding on with both hands. 

Stamina Drain Rate is the base rate stamina is reduced when climbing with a single hand. 

I also considered adding a "Grip Difficulty" to the Interactable Objects script to vary how Stamina will be drained, but opted to leave that out for now for simplicity. 

There is also currently an issue that two controllers can't grab the same object, so it is impossible to regenerate stamina while holding on to the same object with both hands. This issue was most apparent when climbing things like the vegetation in the example. If that is fixed in a future update, I believe this script will work without any changes.

There is one last challenge I came across, in that when you have one hand held, and grab with the other, the first grab is no longer active. Since grabbing with both controls would be more of a pinch to zoom effect, rather than climbing, I opted to track the secondary hold as still active if the controller position hasn't moved more than a small distance from its original grab location. This seems to work nicely and allows for both hands to be "holding" while only one actively manipulates the world around you.

I also copied the existing climb scene and added some nice demo visualization effects to show how much climb stamina remains while climbing.

Let me know what your thoughts are, Thanks.

**Comment by kristianpd** [comment]
This seems far too custom in my opinion to warrant VRTK core. The original PR was closed and deleted and this issue is old. 

I think we should close this issue.

**Comment by reznovVR** [comment]
I agree this is kinda project specific feature instead of a generic one and can already be done via events and custom code(?).

**Comment by TheLazyLemur** [comment]
Does this issue still apply?

**Comment by thestonefox** [comment]
I think the consensus is the feature is too specific. essentially in VRTK v4 you could recreate something like this by using countdown timers and just ungrabbing after the timer expired.
